
classdef JointSingleCommand < ros.Message
    %JointSingleCommand MATLAB implementation of interbotix_xs_msgs/JointSingleCommand
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'interbotix_xs_msgs/JointSingleCommand' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '79b74399c9cdcc4c0be32d540424ed2e' % The MD5 Checksum of the message definition
        PropertyList = { 'Name' 'Cmd' } % List of non-constant message properties
        ROSPropertyList = { 'name' 'cmd' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Name
        Cmd
    end
    methods
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'JointSingleCommand', 'Name');
            obj.Name = char(val);
        end
        function set.Cmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'JointSingleCommand', 'Cmd');
            obj.Cmd = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.interbotix_xs_msgs.JointSingleCommand.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.interbotix_xs_msgs.JointSingleCommand(strObj);
        end
    end
end
