
classdef JointTemps < ros.Message
    %JointTemps MATLAB implementation of interbotix_xs_msgs/JointTemps
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'interbotix_xs_msgs/JointTemps' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2c3b043513eb09ccdff55ab4d97383c3' % The MD5 Checksum of the message definition
        PropertyList = { 'Names' 'Temps' } % List of non-constant message properties
        ROSPropertyList = { 'names' 'temps' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Names
        Temps
    end
    methods
        function set.Names(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'JointTemps', 'Names');
            obj.Names = cell(val);
        end
        function set.Temps(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = int32.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'JointTemps', 'Temps');
            obj.Temps = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.interbotix_xs_msgs.JointTemps.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.interbotix_xs_msgs.JointTemps(strObj);
        end
    end
end
