
classdef OperatingModesRequest < ros.Message
    %OperatingModesRequest MATLAB implementation of interbotix_xs_msgs/OperatingModesRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'interbotix_xs_msgs/OperatingModesRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'cb68bef3d517c840b0a5cc0f73d64e36' % The MD5 Checksum of the message definition
        PropertyList = { 'CmdType' 'Name' 'Mode' 'ProfileType' 'ProfileVelocity' 'ProfileAcceleration' } % List of non-constant message properties
        ROSPropertyList = { 'cmd_type' 'name' 'mode' 'profile_type' 'profile_velocity' 'profile_acceleration' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        CmdType
        Name
        Mode
        ProfileType
        ProfileVelocity
        ProfileAcceleration
    end
    methods
        function set.CmdType(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'OperatingModesRequest', 'CmdType');
            obj.CmdType = char(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'OperatingModesRequest', 'Name');
            obj.Name = char(val);
        end
        function set.Mode(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'OperatingModesRequest', 'Mode');
            obj.Mode = char(val);
        end
        function set.ProfileType(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'OperatingModesRequest', 'ProfileType');
            obj.ProfileType = char(val);
        end
        function set.ProfileVelocity(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OperatingModesRequest', 'ProfileVelocity');
            obj.ProfileVelocity = int32(val);
        end
        function set.ProfileAcceleration(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OperatingModesRequest', 'ProfileAcceleration');
            obj.ProfileAcceleration = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.interbotix_xs_msgs.OperatingModesRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.interbotix_xs_msgs.OperatingModesRequest(strObj);
        end
    end
end
