
classdef TurretJoy < ros.Message
    %TurretJoy MATLAB implementation of interbotix_xs_msgs/TurretJoy
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'interbotix_xs_msgs/TurretJoy' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'cac3aec45a4ead9e4b41e201bb45d797' % The MD5 Checksum of the message definition
        PropertyList = { 'PanCmd' 'TiltCmd' 'SpeedCmd' 'SpeedToggleCmd' } % List of non-constant message properties
        ROSPropertyList = { 'pan_cmd' 'tilt_cmd' 'speed_cmd' 'speed_toggle_cmd' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        PANCCW = int8(1)
        PANCW = int8(2)
        TILTUP = int8(3)
        TILTDOWN = int8(4)
        PANTILTHOME = int8(5)
        SPEEDINC = int8(6)
        SPEEDDEC = int8(7)
        SPEEDCOURSE = int8(8)
        SPEEDFINE = int8(9)
    end
    properties
        PanCmd
        TiltCmd
        SpeedCmd
        SpeedToggleCmd
    end
    methods
        function set.PanCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TurretJoy', 'PanCmd');
            obj.PanCmd = int8(val);
        end
        function set.TiltCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TurretJoy', 'TiltCmd');
            obj.TiltCmd = int8(val);
        end
        function set.SpeedCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TurretJoy', 'SpeedCmd');
            obj.SpeedCmd = int8(val);
        end
        function set.SpeedToggleCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TurretJoy', 'SpeedToggleCmd');
            obj.SpeedToggleCmd = int8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.interbotix_xs_msgs.TurretJoy.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.interbotix_xs_msgs.TurretJoy(strObj);
        end
    end
end
