
classdef ArmJoy < ros.Message
    %ArmJoy MATLAB implementation of interbotix_xs_msgs/ArmJoy
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'interbotix_xs_msgs/ArmJoy' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '09eb0cc37cce12e41a0f984f2c2f53cd' % The MD5 Checksum of the message definition
        PropertyList = { 'EeXCmd' 'EeYCmd' 'EeZCmd' 'EeRollCmd' 'EePitchCmd' 'WaistCmd' 'GripperCmd' 'PoseCmd' 'SpeedCmd' 'SpeedToggleCmd' 'GripperPwmCmd' 'TorqueCmd' } % List of non-constant message properties
        ROSPropertyList = { 'ee_x_cmd' 'ee_y_cmd' 'ee_z_cmd' 'ee_roll_cmd' 'ee_pitch_cmd' 'waist_cmd' 'gripper_cmd' 'pose_cmd' 'speed_cmd' 'speed_toggle_cmd' 'gripper_pwm_cmd' 'torque_cmd' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        EEXINC = int8(1)
        EEXDEC = int8(2)
        EEYINC = int8(3)
        EEYDEC = int8(4)
        EEZINC = int8(5)
        EEZDEC = int8(6)
        EEROLLCCW = int8(7)
        EEROLLCW = int8(8)
        EEPITCHUP = int8(9)
        EEPITCHDOWN = int8(10)
        WAISTCCW = int8(11)
        WAISTCW = int8(12)
        GRIPPEROPEN = int8(13)
        GRIPPERCLOSE = int8(14)
        HOMEPOSE = int8(15)
        SLEEPPOSE = int8(16)
        SPEEDINC = int8(17)
        SPEEDDEC = int8(18)
        SPEEDCOURSE = int8(19)
        SPEEDFINE = int8(20)
        GRIPPERPWMINC = int8(21)
        GRIPPERPWMDEC = int8(22)
        TORQUEON = int8(23)
        TORQUEOFF = int8(24)
    end
    properties
        EeXCmd
        EeYCmd
        EeZCmd
        EeRollCmd
        EePitchCmd
        WaistCmd
        GripperCmd
        PoseCmd
        SpeedCmd
        SpeedToggleCmd
        GripperPwmCmd
        TorqueCmd
    end
    methods
        function set.EeXCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'EeXCmd');
            obj.EeXCmd = int8(val);
        end
        function set.EeYCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'EeYCmd');
            obj.EeYCmd = int8(val);
        end
        function set.EeZCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'EeZCmd');
            obj.EeZCmd = int8(val);
        end
        function set.EeRollCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'EeRollCmd');
            obj.EeRollCmd = int8(val);
        end
        function set.EePitchCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'EePitchCmd');
            obj.EePitchCmd = int8(val);
        end
        function set.WaistCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'WaistCmd');
            obj.WaistCmd = int8(val);
        end
        function set.GripperCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'GripperCmd');
            obj.GripperCmd = int8(val);
        end
        function set.PoseCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'PoseCmd');
            obj.PoseCmd = int8(val);
        end
        function set.SpeedCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'SpeedCmd');
            obj.SpeedCmd = int8(val);
        end
        function set.SpeedToggleCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'SpeedToggleCmd');
            obj.SpeedToggleCmd = int8(val);
        end
        function set.GripperPwmCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'GripperPwmCmd');
            obj.GripperPwmCmd = int8(val);
        end
        function set.TorqueCmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ArmJoy', 'TorqueCmd');
            obj.TorqueCmd = int8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.interbotix_xs_msgs.ArmJoy.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.interbotix_xs_msgs.ArmJoy(strObj);
        end
    end
end
