
classdef JointTrajectoryCommand < ros.Message
    %JointTrajectoryCommand MATLAB implementation of interbotix_xs_msgs/JointTrajectoryCommand
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'interbotix_xs_msgs/JointTrajectoryCommand' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '039c1a8f9200d555267cf39243b5e969' % The MD5 Checksum of the message definition
        PropertyList = { 'Traj' 'CmdType' 'Name' } % List of non-constant message properties
        ROSPropertyList = { 'traj' 'cmd_type' 'name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.trajectory_msgs.JointTrajectory' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Traj
        CmdType
        Name
    end
    methods
        function set.Traj(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.trajectory_msgs.JointTrajectory'};
            validateattributes(val, validClasses, validAttributes, 'JointTrajectoryCommand', 'Traj')
            obj.Traj = val;
        end
        function set.CmdType(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'JointTrajectoryCommand', 'CmdType');
            obj.CmdType = char(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'JointTrajectoryCommand', 'Name');
            obj.Name = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.interbotix_xs_msgs.JointTrajectoryCommand.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.interbotix_xs_msgs.JointTrajectoryCommand(strObj);
        end
    end
end
