
classdef RebootRequest < ros.Message
    %RebootRequest MATLAB implementation of interbotix_xs_msgs/RebootRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'interbotix_xs_msgs/RebootRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '229067e7bfb48bf403b702d5f7f1ee93' % The MD5 Checksum of the message definition
        PropertyList = { 'CmdType' 'Name' 'Enable' 'SmartReboot' } % List of non-constant message properties
        ROSPropertyList = { 'cmd_type' 'name' 'enable' 'smart_reboot' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        CmdType
        Name
        Enable
        SmartReboot
    end
    methods
        function set.CmdType(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'RebootRequest', 'CmdType');
            obj.CmdType = char(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'RebootRequest', 'Name');
            obj.Name = char(val);
        end
        function set.Enable(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RebootRequest', 'Enable');
            obj.Enable = logical(val);
        end
        function set.SmartReboot(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RebootRequest', 'SmartReboot');
            obj.SmartReboot = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.interbotix_xs_msgs.RebootRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.interbotix_xs_msgs.RebootRequest(strObj);
        end
    end
end
