
classdef RobotInfoRequest < ros.Message
    %RobotInfoRequest MATLAB implementation of interbotix_xs_msgs/RobotInfoRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'interbotix_xs_msgs/RobotInfoRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '81f769be1f5fc7b940e801609273b513' % The MD5 Checksum of the message definition
        PropertyList = { 'CmdType' 'Name' } % List of non-constant message properties
        ROSPropertyList = { 'cmd_type' 'name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        CmdType
        Name
    end
    methods
        function set.CmdType(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'RobotInfoRequest', 'CmdType');
            obj.CmdType = char(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'RobotInfoRequest', 'Name');
            obj.Name = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.interbotix_xs_msgs.RobotInfoRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.interbotix_xs_msgs.RobotInfoRequest(strObj);
        end
    end
end
