
classdef TorqueEnableRequest < ros.Message
    %TorqueEnableRequest MATLAB implementation of interbotix_xs_msgs/TorqueEnableRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'interbotix_xs_msgs/TorqueEnableRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '023452ade9f3d4979c75bd4e0d60f0c9' % The MD5 Checksum of the message definition
        PropertyList = { 'CmdType' 'Name' 'Enable' } % List of non-constant message properties
        ROSPropertyList = { 'cmd_type' 'name' 'enable' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        CmdType
        Name
        Enable
    end
    methods
        function set.CmdType(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'TorqueEnableRequest', 'CmdType');
            obj.CmdType = char(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'TorqueEnableRequest', 'Name');
            obj.Name = char(val);
        end
        function set.Enable(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TorqueEnableRequest', 'Enable');
            obj.Enable = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.interbotix_xs_msgs.TorqueEnableRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.interbotix_xs_msgs.TorqueEnableRequest(strObj);
        end
    end
end
